# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    abb_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

abb_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      joint1: {p: 100.0, i: 0.0, d: 1.0}
      joint2: {p: 100.0, i: 0.0, d: 1.0}
      joint3: {p: 100.0, i: 0.0, d: 1.0}
      joint4: {p: 100.0, i: 0.0, d: 1.0}
      joint5: {p: 100.0, i: 0.0, d: 1.0}
      joint6: {p: 100.0, i: 0.0, d: 1.0}

diff_drive_controller:
  ros__parameters:
    publish_rate: 100.0
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 1.23 
    wheel_radius: 0.05

    use_stamped_vel: false
